import sys

path = r"D:\WebDev\WEBProg\Project\bhasabridge\frontend\src\components\Lessons\Lessons.jsx"

with open(path, "rb") as f:
    raw = f.read()

# The file bytes are valid UTF-8 but some sequences were written as
# Latin-1/Windows-1252 mojibake. Re-encode to fix them.
# Strategy: decode as latin-1 (lossless), then fix known bad patterns.

content = raw.decode("utf-8", errors="replace")

# (mojibake, correct character) pairs
# Generated by encoding the correct char as UTF-8 and reading it as Latin-1
pairs = [
    # emoji / special chars that appear corrupted in the file
    ("\u00e2\u00a4\u00ef\u00bf\u00bd",  "\u2764\ufe0f"),   # broken heart attempt 1
    ("\u00c3\u00a2\u00c2\u00a4\u00c3\u00af\u00c2\u00b8",   "\u2764\ufe0f"),   # broken heart attempt 2
]

# Simpler: just replace the literal byte patterns by reading raw bytes
# mojibake bytes for common emoji / chars encoded wrong

FIX = {
    # ❤️  -> UTF-8: E2 9D A4 EF B8 8F, mojibake (as if read as latin1): â\x9d¤ï¸\x8f
    b"\xe2\x9d\xa4\xef\xb8\x8f": "\u2764\ufe0f",
    # 🖤  -> UTF-8: F0 9F 96 A4  
    b"\xf0\x9f\x96\xa4": "\U0001f5a4",
    # 🎮  -> UTF-8: F0 9F 8E AE
    b"\xf0\x9f\x8e\xae": "\U0001f3ae",
    # 🎉  -> UTF-8: F0 9F 8E 89
    b"\xf0\x9f\x8e\x89": "\U0001f389",
    # 💡  -> UTF-8: F0 9F 92 A1
    b"\xf0\x9f\x92\xa1": "\U0001f4a1",
    # ✅  -> UTF-8: E2 9C 85
    b"\xe2\x9c\x85": "\u2705",
    # ❌  -> UTF-8: E2 9D 8C
    b"\xe2\x9d\x8c": "\u274c",
    # →  -> UTF-8: E2 86 92
    b"\xe2\x86\x92": "\u2192",
    # ←  -> UTF-8: E2 86 90
    b"\xe2\x86\x90": "\u2190",
    # …  -> UTF-8: E2 80 A6
    b"\xe2\x80\xa6": "\u2026",
    # —  -> UTF-8: E2 80 94
    b"\xe2\x80\x94": "\u2014",
    # ✓  -> UTF-8: E2 9C 93
    b"\xe2\x9c\x93": "\u2713",
    # ✗  -> UTF-8: E2 9C 97
    b"\xe2\x9c\x97": "\u2717",
}

# Work on raw bytes: detect and replace corrupted multi-byte sequences
# that appear as UTF-8 encoded Latin-1 mojibake
# e.g., if â¤ï¸ appears, its bytes in UTF-8 are:
#   â = C3 A2  (U+00E2 in mojibake, which is â)
#   ¤ = C2 A4  (U+00A4)
#   ï = C3 AF  (U+00EF)
#   ¸ = C2 B8  (U+00B8)
# That's the double-encoded form. But actually the file IS valid UTF-8 but
# contains literal mojibake text sequences.

# Decode the raw bytes as latin-1 to get Unicode codepoints matching byte values
latin1_content = raw.decode("latin-1")

# Now the mojibake patterns are visible as their original Latin-1 chars
# For ❤️ (UTF-8: E2 9D A4 EF B8 8F) read as latin-1: â\x9d¤ï¸\x8f
# But \x9d is a control char and won't appear as â€¦ style mojibake.
# Actually the file shows "â¤ï¸" which means:
#   â = U+00E2  (UTF-8: C3 A2 but as single byte: E2)
#   ¤ = U+00A4  (A4)
#   ï = U+00EF  (EF)
#   ¸ = U+00B8  (B8)
# So the bytes in the file are: E2 A4 EF B8 ... but that's not valid UTF-8 for ❤️
# ❤️  UTF-8 is: E2 9D A4 EF B8 8F
# Read as latin-1 those bytes become chars: \xe2 \x9d \xa4 \xef \xb8 \x8f
# Which in latin-1 Unicode are: U+00E2 U+009D U+00A4 U+00EF U+00B8 U+008F
# U+009D and U+008F are control chars, not â¤ï¸.
# 
# So actually the file shows â¤ï¸ meaning the bytes are the 2-byte UTF-8 encoding
# of each character:  â=U+00E2 -> C3 A2, ¤=U+00A4 -> C2 A4, ï=U+00EF -> C3 AF, ¸=U+00B8 -> C2 B8
# So the file has: C3 A2  C2 A4  C3 AF  C2 B8
# That's the UTF-8 encoding of U+00E2 U+00A4 U+00EF U+00B8
# Which are the BYTE VALUES of ❤️'s UTF-8 encoding (E2 A4... wait that's only 4 bytes for ❤️ but ❤️ is E2 9D A4 EF B8 8F)
# 
# Hmm. Let me just try finding the actual byte sequence in the file.

print("File size:", len(raw), "bytes")

# Search for known patterns
heart_utf8 = "\u2764\ufe0f".encode("utf-8")
print("❤️  UTF-8 bytes:", heart_utf8.hex())

# Find occurrences in raw  
idx = raw.find(heart_utf8)
print("Direct ❤️  found at:", idx)

# Also check for double-encoded version (UTF-8 bytes encoded as UTF-8 again)
# E2 9D A4 EF B8 8F  -> encode each byte as latin-1 char -> encode each of those as UTF-8
single = bytes([0xE2, 0x9D, 0xA4, 0xEF, 0xB8, 0x8F])
double_encoded = single.decode("latin-1").encode("utf-8")
print("Double-encoded ❤️  bytes:", double_encoded.hex())
idx2 = raw.find(double_encoded)
print("Double-encoded ❤️  found at:", idx2)

# Check actual bytes around line 167
lines = raw.split(b"\n")
for i, line in enumerate(lines[160:175], start=161):
    if b"heart" in line.lower() or (b"\xe2" in line):
        print(f"Line {i}: {line}")
